apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    rbac.authorization.kubernetes.io/autoupdate: "true"
    openshift.io/description: "This ClusterRole was is created by default, but refers to an SCC that doesn't exist. This ClusterRole will likely be removed in a future release."
  name: system:openshift:scc:hostmount
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostmount
  resources:
  - securitycontextconstraints
  verbs:
  - use
